version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test123
      ME_CONFIG_MONGODB_URL: mongodb://root:test123@mongo:27017/
    ports:
      - "8081:8081"

  gateway:
    build: ./gateway
    restart: always
    ports:
      - "8082:443"

  app:
    build: .
    restart: always
    environment:
      MONGO_URL: "mongodb://root:test123@mongo"
    ports:
      - "8080:8080"
