version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123
    ports:
      - "27017:27017"

  app:
    image: eventbus
    restart: always
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: test123
      MONGO_HOST: mongo
    ports:
      - "8080:8080"
